# https://hub.docker.com/r/freeipa/freeipa-server
# https://manpages.ubuntu.com/manpages/focal/man1/ipa-server-install.1.html
version: '3'
services:
  freeipa-server:
    image: freeipa/freeipa-server:fedora-39-4.11.0
    container_name: freeipa-server
    hostname: freeipa-server.gaich.com
    restart: always
    volumes:
      - ./freeipa-data:/data
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    #env_file:
      #- .env
    ports:
        - "443:443"
        - "389:389"
        - "636:636"
        - "88:88"
        - "88:88/udp"
        - "464:464"
        - "464:464/udp"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0


